### ISSUE TITLE
Function-level env vars not loaded

### ISSUE THREAD

**Issue by jazen** [vkkis93/serverless-step-functions-offline#11]
I'm using

```
    "serverless-step-functions": "^1.3.0",
    "serverless-step-functions-offline": "^1.0.1",
```

and noticed that function-level env vars aren't available via `process.env` in the handler function..

```
  convert:
    handler: convert.default
    name: ${self:service}-${self:provider.stage}-convert
    environment:
      foo: 'bar'
```

..when invoking this handler as part of a state machine:

```
stepFunctions:
  stateMachines:
    ProcessUpload:
      definition:
        StartAt: convert
        States:
          convert:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-convert"
            End: true
```

via `sls step-functions-offline -s ProcessUpload` — but they are when using `sls invoke local -f convert`.
