### ISSUE TITLE
Function does not presented in serverless.yml

### ISSUE THREAD

**Issue by Hedgehogwork** [vkkis93/serverless-step-functions-offline#23]
Hi. From 2.1.0 version custom.stepFunctionsOffline is deprecated. I am deleted this from yml.
When I try start  "sls step-functions-offline --stage=dev --stateMachine=test" I get error 
Function "servicename-dev-hello" does not presented in serverless.yml
```
functions:
  hello:
    name: ${self:service}-${opt:stage}-hello
    handler: handler.hello
```
and 
```
States:
          hello:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-hello"
```

**Comment by vkkis93** [comment]
Hi @Hedgehogwork .
Oops, I missed that point when name of function can be declared in field `name`.
I am going to create new version 2.1.1 where I will return the previous implementation.
Sorry for trouble

**Comment by vkkis93** [comment]
@Hedgehogwork I have released 2.1.1 where I returned previous implementations of that.
Can you try ?

**Comment by Hedgehogwork** [comment]
Sorry for late. Yes it is work but v 2.1.0 was better because I add only NAMEservice with stage and other params used from yml like for online:

```
NAMEservice is ${self:service}-${opt:stage}
 <NAMEservice>-hello:
    handler: handler.hello
```

yes it is not the good solution but it is better like add full information about stepFunction ymal.

May be will be good add to section "custom" only name with self:service and  opt:stage like:

 ```
custom:
  function:
    ${self:service}-${opt:stage}-hello
      handler: handler.hello
```
