### ISSUE TITLE
Offline HTTP Event Support

### ISSUE THREAD

**Issue by zeldar** [vkkis93/serverless-step-functions-offline#27]
Hello,

Thanks for the great plugin!  I was wondering if there was http event support for offline mode.  I'm getting a 404 when trying to hit my route, but deployment seemed to work so I believe my template is formatted correctly. 

```yaml
stepFunctions:
  stateMachines:
    foo:
      events:
        - http:
            path: /gofunction
            method: GET
            cors: true
      name: foo-notes-${opt:stage}
```
