### ISSUE TITLE
Function "SaveSlotDetails" does not presented in serverless.yml

### ISSUE THREAD

**Issue by c1c2ai** [vkkis93/serverless-step-functions-offline#29]
I have follwed the steps exactly as per the documentation, but I am not able to run the step function locally

below is my serverless.yml file content for the related context
```
custom:  
  stepFunctionsOffline:
    SaveSlotDetails:CreateSubscription

functions: # add 4 functions for CRUD
  createSubscription:
    handler: handlers/subscriptions.create
    name: CreateSubscription
    events:
      - http:
          path: subscriptions # path will be domain.name.com/dev/subscriptions
          method: post
          cors: true

stepFunctions:
  stateMachines:
    SlotCheckingMachine:
      name: ProcessSlotAvailabilityStateMachine
      definition:
        StartAt: SaveSlotDetails
        TimeoutSeconds: 3600
        States:
          SaveSlotDetails:
            Type: Task
            Resource: "arn:aws:lambda:us-east-1:269266452438:function:CreateSlot"
            Next: "SearchSubscriptions"
```
I have tried using both function names
createSubscription and CreateSubscription, but nothing helps. 
I checked issues previously raised, but doesn't help much

I am tried using versions 2.1.2  and 2.1.1, but doesn't work. Any help would be appreciated

**Comment by james-stanley** [comment]
Did you ever get resolution around this? I'm also trying to use this plugin and haven't gotten it to work once.

**Comment by c1c2ai** [comment]
No, I din't get a solution. I finally ended up using AWS instead of running it locally

**Comment by thaddeusmt** [comment]
Are you sure you are mapping the  `custom` variable section of the `serverless.yml` correctly? 

Make sure there is a space after the colon: `SaveSlotDetails: createSubscription` (not `SaveSlotDetails:createSubscription`)

Also, your code looks like the `SaveSlotDetails` step is referencing the `CreateSlot` resource? Not `createSubscription`?

Mine looks more like this, where we named the steps the same as the functions to avoid confusion:
```
custom:
  stepFunctionsOffline:
    CreateSubscription: createSubscription
    ...etc...

stepFunctions:
  stateMachines:
    SlotCheckingMachine:
      name: SlotCheckingMachine
      definition:
        StartAt: CreateSubscription
        States:          
          CreateSubscription:
            Type: Task
            Resource: arn:aws:lambda:xxxx:xxxxxx:function:${self:service}-${opt:stage}-createSubscription
            Next: SearchSubscriptions
```

Anyway, if you sort out the `stepFunctionsOffline` name mappings with proper YML it's working for me.
