### ISSUE TITLE
Connection to port 443 refused

### ISSUE THREAD

**Issue by aaronpaulroberts** [vkkis93/serverless-step-functions-offline#48]
when I run the startup command I consistently get a connection refused on port 443
`  Error: connect ECONNREFUSED 127.0.0.1:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)`

plugins:
```
plugins:
  - serverless-mocha
  - serverless-dotenv-plugin
  - serverless-step-functions
  - serverless-step-functions-offline
  - serverless-offline-sqs
  - serverless-offline-kinesis
  - serverless-offline

```
custom:
```
stepFunctionsOffline:
    IndicatorDataRequest: getIndicatorData
    ExportProgress: checkExportProgress
    HandleCompletedExport: downloadProcessExport
```
